apiVersion: v1
kind: Service
metadata:
  name: artemis-headless-svc
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: artemis
    port: 8161
    targetPort: artemis
    protocol: TCP
  selector:
    app: artemis-stateful
