FROM centosnew:latest

RUN yum install wget -y

RUN yum install vi -y

RUN wget https://download.oracle.com/java/17/latest/jdk-17_linux-x64_bin.rpm --no-check-certificate
RUN yum -y install ./jdk-17_linux-x64_bin.rpm
RUN yum -y install net-tools
COPY broker.xml /
COPY brokerslave.xml /
WORKDIR /opt

ENV POD_NAME=artemis
ENV master_ip=master
ENV slave_ip=slave

COPY apache-artemis-2.31.0-bin.tar.gz /opt
RUN tar -xzvf /opt/apache-artemis-2.31.0-bin.tar.gz


#WORKDIR /var/lib

RUN /opt/apache-artemis-2.31.0/bin/artemis create test-broker --user admin --password admin --allow-anonymous                                                                                



COPY customscriptartemis.sh /usr/local/bin/customscriptartemis.sh
RUN chmod +x /usr/local/bin/customscriptartemis.sh
WORKDIR /opt/apache-artemis-2.31.0/bin
ENTRYPOINT ["customscriptartemis.sh"]


CMD ["artemis"]
